[merge.cicd_gate]
script = "./ci.sh"
auto_resolve = true
retries = 2

[commands]
draft = "file:.vizier/workflows/draft.hcl"
approve = "file:.vizier/workflows/approve.hcl"
merge = "file:.vizier/workflows/merge.hcl"
develop = "file:.vizier/develop.hcl"
commit = "file:.vizier/workflows/commit.hcl"
